version: "3"
services:
  mongo:
    image: "mongo:3"
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    env_file: .elastic.env
    depends_on:
      - mongo
    ulimits:
      memlock:
        soft: -1
        hard: -1
  graylog:
    image: "graylog/graylog:3.0"
    env_file: .gray.env
    ports:
      # Graylog web interface and REST API
      # - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    depends_on:
      - mongo
      - elasticsearch
  nginx:
    build:
      context: .
      dockerfile: DockerfileNginx
    env_file: .nginx.env
    ports:
      - "${APP_PORT}:80"
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - graylog
