version: "3"
services:
  mongo:
    image: mongo:3
    env_file: .env
    volumes:
      - ${DATA_DB}:/data/db
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    env_file: .elastic.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
  graylog:
    image: graylog/graylog:3.3
    env_file: .gray.env
    volumes:
      - ./graylog_volume:/etc/graylog
    ports:
      # Graylog web interface and REST API
      # - 9000:9000
      # Syslog UDP
      - 5140:5140/udp
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    depends_on:
      - mongo
      - elasticsearch
  nginx:
    image: nginx
    env_file: .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${APP_PORT}:80"
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - graylog
